# Make "init" project

CC = gcc
CFLAGS = -Wall -D_DEBUG_ON `sdl-config --cflags`
CXXFLAGS = -Wall `sdl-config --cflags`
LDFLAGS = `sdl-config --libs` -lm -lpthread -lSDL_mixer -lGL -lGLU
SRC = draw.c
OBJ = draw.o
TARGET = draw

all: $(TARGET)

$(TARGET): $(OBJ)
	$(CC) $(LDFLAGS) -o $(TARGET) $(OBJ)

clean:
	rm -f $(TARGET) $(OBJ) core
