application: woongiap
version: 2
runtime: python27
api_version: 1
threadsafe: False

handlers:
- url: /img
  static_dir: pages/img
- url: /css
  static_dir: pages/css
- url: /js
  static_dir: pages/js
- url: /.*
  script: main.py
  
libraries:
- name: django
  version: "1.2"

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'

