######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 10 14:34:49 2008
######################################################################

TEMPLATE = app
TARGET = find_dialog
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += find_dialog.h
SOURCES += find_dialog.cpp main.cpp
